# Generated by Django 4.2.2 on 2024-10-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='session_id',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Id сессии'),
        ),
    ]
