# Generated by Django 4.2.2 on 2024-10-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_payment_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_registration',
            field=models.DateField(auto_now=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последней авторизации'),
        ),
    ]
