# Generated by Django 4.2.2 on 2024-10-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_date_registration_alter_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_registration',
        ),
    ]
